title: Welcome to My Projects
description: Public Data, Thesis, Crawling
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://benben103.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    배현준
author-image:   1.jpg
author-job:
author-email:   beejuny@gmail.com # Add your email for contant form.
author-twitter: # Add your twitter account
about-author:   안녕하세요. 중부대학교 미디어커뮤니케이션학과 4학년 재학 중인 배현준입니다. 현재 데이터 분석과 코딩을 공부 중입니다.

# Social settings
social-twitter:
social-facebook:
social-github: benben103
social-pinterest:
social-instagram: benkidish103
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
